"""init

Revision ID: 215fa5ed0cc3
Revises: 
Create Date: 2024-06-20 18:56:30.003404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215fa5ed0cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=450), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='e_commerce'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='e_commerce'
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['e_commerce.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='e_commerce'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('image1', sa.String(length=225), nullable=False),
    sa.Column('image2', sa.String(length=225), nullable=True),
    sa.Column('image3', sa.String(length=225), nullable=True),
    sa.Column('image4', sa.String(length=225), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['e_commerce.product_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='e_commerce'
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=450), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['e_commerce.product_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['e_commerce.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='e_commerce'
    )
    op.create_table('styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['e_commerce.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='e_commerce'
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['e_commerce.products.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['e_commerce.product_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['e_commerce.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='e_commerce'
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_type_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=225), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['e_commerce.orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['e_commerce.products.id'], ),
    sa.ForeignKeyConstraint(['product_type_id'], ['e_commerce.product_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='e_commerce'
    )
    op.create_table('style_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_type_id'], ['e_commerce.product_types.id'], ),
    sa.ForeignKeyConstraint(['style_id'], ['e_commerce.styles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='e_commerce'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_items', schema='e_commerce')
    op.drop_table('order_items', schema='e_commerce')
    op.drop_table('favorites', schema='e_commerce')
    op.drop_table('styles', schema='e_commerce')
    op.drop_table('reviews', schema='e_commerce')
    op.drop_table('products', schema='e_commerce')
    op.drop_table('orders', schema='e_commerce')
    op.drop_table('users', schema='e_commerce')
    op.drop_table('product_types', schema='e_commerce')
    # ### end Alembic commands ###
